version: "3.7"

# networks:
#   rentx-network:
#     driver: bridge

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    # networks:
    #   - rentx-network

  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - database
    # networks:
    #   - rentx-network

volumes:
  pgdata:
    driver: local
